inherit_from: env/habitat/configs/replica.yaml
mapping:
  bound:  [[-10,10],[-1.5,4],[-10,10]] 
  marching_cubes_bound:  [[-10,10],[-1.5,4],[-10,10]] 
  map_every: 5
  lr_uncert: 0.01
  first_mesh: False # don't save first mesh
  

mesh: 
  vis: 500 # don't save meshes 

grid:
  enc: 'HashGrid'
  hash_size: 16
  voxel_color: 0.08
  voxel_sdf: 0.02
  uncertainty: 'grid' # 'gird', 'tensor', or 'none'
  voxel_uncert: 0.1
  
cam: 
  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 10.0 # this is for calculating sdf loss
  max_depth: 10.0 # where I cut my depth pixel value

data:
  output: results/mapping
  exp_name: Oct_17_resizeUncert

training:
  rgb_weight: 5.0 #5.0 by default
  depth_weight: 0.1
  sdf_weight: 1000
  fs_weight: 10 # 10 by default
  smooth_weight: 0.000001
  uncert_weight: 0.005 # Naruto = 0.005


