inherit_from: configs/replica.yaml
mapping:
  bound:  [[-10,10],[-1,3],[-10,10]] 
  marching_cubes_bound:  [[-10,10],[-1,3],[-10,10]] 
  keyframe_every: 1
  map_every: 1
  

mesh: 
  render_color: True
  vis: 25 #25
  voxel: 0.02 


cam: 
  H: 360
  W: 640

  fx: 498.37325
  fy: 498.37325
  cx: 327.03568499999994
  cy: 181.04722166666664

  crop_edge: 0
  near: 0
  far: 5
  depth_trunc: 100. # this is for calculating sdf loss
  max_depth: 10000. # where I cut my depth pixel value


data:
  host: desktop # or laptop
  wait_time: 0. # how long desktop should wait per iteration
  num_frames_laptop: 2500 # laptop
  num_frames_desktop: 10000 # 4090 desktop
  downsample: 1
  sc_factor: 1
  output: output/turtlebot
  exp_name: single_oogway_offical
  load_path: output/Apartment/apartment_centralized/agent_0/checkpoint12594.pt


training:
  rgb_weight: 5.0
  depth_weight: 0.1
  sdf_weight: 1000
  fs_weight: 10 # 10 by default
  smooth_weight: 0.000001

multi_agents:
  com_every: 1 
  distributed_algorithm: 'CADMM'
  rho:  0.0001 
  track_uncertainty: True
  fix_decoder: False
  #alpha: 0.15 # DSGD
  alpha: 0.02 # DSGT

